# -*- coding: utf-8 -*-
"""2. Sample Implementation-Chatbots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HuMX2X-RTJ8tsu3yg1CAa1vFrHpfJV-8

#Sample Implementation-Chatbots
##Korea Tourism ChatBot
###20/11/2025
"""

def main_menu():
  print("\n---Hello, Welcome to Dabin's Korea Tourism Bot! \n What would you love to know? ---")
  print("1) Place to Visit in Korea")
  print("2) K-Food?")
  print("3) K-Beauty?")
  print("4) K-Drinking Culture?") 
  print("5) Exit")

# ------------------------------
# 1) Places to Visit → Mood
# ------------------------------

def place_menu():
  print("\n---Not only SEOUL, but also there are so many beautiful cities in Korea. Which kind of vibe do you prefer? ---")
  print("1) City")
  print("2) Beach")
  print("3) Nature")
  print("4) Traditional")
  print("5) Back to the Main Menu") 


# City
def recommend_city():
    print("\n✨ Recommended City Destinations ✨")
    print("- Seoul")
    print("- Busan")
    print("- Incheon")
    input("\nPress Enter to go back.")


# Beach
def recommend_beach():
    print("\n🌊 Recommended Beach Destinations 🌊")
    print("- Busan: Haeundae & Gwangalli beaches")
    print("- Jeju: Hamdeok & Hyeopjae beaches")
    print("- Gangneung: Clean water, chill vibes")
    input("\nPress Enter to go back.")


# Nature
def recommend_nature():
    print("\n🌲 Recommended Nature Destinations 🌲")
    print("- Jeju Island: Waterfalls, Hallasan, lava tubes")
    print("- Sokcho: Seoraksan hiking")
    print("- Boseong: Green tea fields")
    input("\nPress Enter to go back.")


# Traditional
def recommend_traditional():
    print("\n🏮 Recommended Traditional Destinations 🏮")
    print("- Gyeongju: Ancient Silla temples & tombs")
    print("- Andong: Hahoe Folk Village")
    print("- Jeonju: Hanok Village + famous food")
    input("\nPress Enter to go back.")

# ------------------------------
# 2) K-Food
# ------------------------------

def food_menu():
  print("\n---K-Food---")
  print("1) Must-Try Korean Dishes")
  print("2) Street Food")
  print("3) Desserts")
  print("4) Regional Specialties")
  print("5) Back to the Main Menu")

#1)Must-Try
def must_try():
  print("\n🍲 Popular K-Food Recommendations 🍲")
  print("- Korean BBQ")
  print("- Bibimbap")
  print("- Tteokbokki")
  input("\nPress Enter to go back.")

#2)Street Food
def street_food():
  print("\n🍲 Go to the GWANGJANG MARKET for the street food! 🍲")
  print("- Bindaetteok (Mung Bean Pancakes)")
  print("- Kalguksu (Korean knife-cut noodle soup)")
  print("- Kimbap (bite-size dried seaweed rolls)")
  input("\nPress Enter to go back.")

#3)Desserts
def desserts():
  print("\n🍰 Korean Desserts 🍰")
  print("- Bingsu (try Sulbing!)")
  print("- Hotteok (Gwangjang Market)")
  print("- Dalgona (Squid Game candy!)")
  input("\nPress Enter to go back.")

#4)Regional Specialties
def regional_specialties():
  print("\n🍲 When you visit another cities in Korea! 🍲")
  print("- Andong Jjimdak (braised chicken) from Andong ")
  print("- Jeonju Bibimbap from Jeonju")
  print("- Heukdwaeji (black pork) from Jeju")
  input("\nPress Enter to go back.")

# ------------------------------
# 3) K-Beauty
# ------------------------------

def beauty_menu():
  print("\n---K-beauty is becoming increasingly popular. To keep up with the trend, we should explore K-beauty, right?---")
  print("1) Famous K-Beauty Shops")
  print("2) Popular Products")
  print("3) For an exotic Skin-Care experience")
  print("4) Back to the Main Menu")

#1)K-Beauty Shops
def k_beauty_shops():
  print("\n💄 K-Beauty Shop 💄")
  print("- Olive Young (best in Hongdae!)")
  input("\nPress Enter to go back.")

#2)Popular Products
def k_beauty_product():
  print("\n💄 Must-Buy K-Beauty Products 💄")
  print("- Biodance Collagen Mask")
  print("- Aestura Atobarrier Cream")
  print("- Laneige Lip Sleeping Mask")
  input("\nPress Enter to go back.")

#3)For an exotic Skin-Care Experience
def k_beauty_experience():
  print("\n💄 Unique K-Beauty Experiences 💄")
  print("- Personal Color Analysis")
  print("- Rejuran Skincare Treatments")
  input("\nPress Enter to go back.")


# ------------------------------
# 4) K-Drinking Culture
# ------------------------------

def drinking_menu():
  print("\n---There are people who never been to Korea, but there is no one who only been once. It's because of Korean drinking culture! Let's learn about it more---")
  print("1) Soju & Somek & Makgeolli")
  print("2) Anju (Food with Alcohol)")
  print("3) Korean Drinking Etiquette")
  print("4) Drinking Games")
  print("5) 24/7 Night Life")
  print("6) Back to the Main Menu")

#1) Soju & Somek
def soju_somek_makgeolli():
  print("\n🍶 K-Drinking Culture: Soju, Somek & Makgeolli 🍶")
  print("• Soju: Korea’s most famous liquor—smooth, cheap, and easy to drink.")
  print("• Somek: A mix of soju + beer, popular at gatherings and parties.")
  print("• Makgeolli: A traditional rice wine with a milky texture and soft sweetness.")
  print("\nTip: Soju tastes great with Korean BBQ, and Makgeolli is best with savory pancakes!")
  input("\nPress Enter to go back.")

#2) Anju
def anju():
  print("\n🍢 Anju: Korean Food That Goes With Alcohol 🍢")
  print("• Koreans never drink without food—this is called 'anju'.")
  print("• Popular anju: Korean fried chicken, tteokbokki, seafood stew, pork belly, and jokbal (pig’s feet).")
  print("• Each alcohol has a perfect match—for example, chicken with beer and pancakes with makgeolli.")
  input("\nPress Enter to go back.")

#3) Korean Drinking Etiquette
def drinking_etiquette():
  print("\n🙏 Korean Drinking Etiquette 🙏")
  print("• Pour drinks for others—never pour your own glass.")
  print("• Use two hands when receiving a drink from someone older.")
  print("• Turn your head slightly away when drinking in front of elders.")
  print("• Empty glasses mean you're ready for the next round!")
  input("\nPress Enter to go back.")

#4) Drinking Games
def drinking_games():
  print("\n🎲 Korean Drinking Games 🎲")
  print("• Korean parties often include fun games to keep the mood lively.")
  print("• Popular games:")
  print("   - Baskin Robbins 31")
  print("   - Titanic (sinking shot glass)")
  print("   - The Thumb Game")
  print("   - Silent 007")
  print("• Easy to play and perfect for making new friends!")
  input("\nPress Enter to go back.")

#5)24/7 Night Life
def night_life():
  print("\n🌃 Korea's 24/7 Nightlife 🌃")
  print("• Korea, especially Seoul and Busan, has a nightlife that never sleeps.")
  print("• Bars, clubs, convenience stores, and street food vendors run all night.")
  print("• After drinking, Koreans often enjoy ‘yaja’ food like ramen, gimbap, or hangover soup.")
  print("• Safe, lively, and full of energy—an unforgettable experience!")
  input("\nPress Enter to go back.")

# --- Start Chatbot ---

def run_chatbot():
  while True:
    main_menu()
    choice = input("\nChoose an option: ")

    #Exit
    if choice == "5":
      print("\nThank you for visiting Dabin's Korea Tourism Bot! Bye:)")
      break

    #1) Place to visit
    elif choice == "1":
      while True:
        place_menu()
        sub = input("\nYour Choice: ")
        if sub == "1":
          recommend_city()
        elif sub == "2":
          recommend_beach()
        elif sub == "3":
            recommend_nature()
        elif sub == "4":
            recommend_traditional()
        elif sub == "5":
            break
        else:
            print("Please enter the number between 1-5!")

    #2) K-Food
    elif choice == "2":
      while True:
        food_menu()
        sub = input("\nYour Choice: ")
        if sub == "1":
          must_try()
        elif sub == "2":
          street_food()
        elif sub == "3":
          desserts()
        elif sub == "4":
          regional_specialties()
        elif sub == "5":
          break
        else:
          print("Please enter the number between 1-5!")

    # 3) K-Beauty
    elif choice == "3":
        while True:
            beauty_menu()
            sub = input("\nYour choice: ")
            if sub == "1":
                k_beauty_shops()
            elif sub == "2":
                k_beauty_product()
            elif sub == "3":
                k_beauty_experience()
            elif sub == "4":
                break
            else:
                print("Please enter the number between 1-4!")

    # 4) K-Drinking Culture
    elif choice == "4":
        while True:
            drinking_menu()
            sub = input("\nYour choice: ")
            if sub == "1":
                soju_somek_makgeolli()
            elif sub == "2":
                anju()
            elif sub == "3":
                drinking_etiquette()
            elif sub == "4":
                drinking_games()
            elif sub == "5":
                night_life()
            elif sub == "6":
                break
            else:
                print("Please enter the number between 1-6!")

    else:
        print("Invalid choice. Please try again!")

# Run bot
run_chatbot()